language: python
python:
  - "3.4"

env:
  global:
    - PATH=$HOME/miniconda/bin:$PATH

before_install:
  # Install Miniconda
  - wget https://raw.githubusercontent.com/m-labs/artiq/master/.travis/get-anaconda.sh
  - chmod +x get-anaconda.sh
  - ./get-anaconda.sh
  - source $HOME/miniconda/bin/activate py34
  - conda install anaconda-client numpydoc
install:
  # Install iverilog package.
  # - "sudo add-apt-repository -y ppa:mithro/iverilog-backport"
  # - "sudo apt-get update"
  # - "sudo apt-get install iverilog"
  # - "iverilog -v; true"
  # Build the vpi module.
  # - "(cd vpi; make; sudo make install)"
  # Install verilator package
  - "sudo apt-get install verilator"
  - "verilator --version; true"
  # Build and install Migen conda package
  - "conda build conda/migen"
  - "conda install migen --use-local"

script:
  # Run tests
  - "python setup.py test"
  # Generate HTML documentation
  - "make -C doc html"

after_success:
  # Upload Migen conda package to binstar
  - anaconda login --hostname $(hostname) --username $binstar_login --password $binstar_password
  - anaconda upload --user $binstar_login --channel dev --force $HOME/miniconda/conda-bld/linux-64/migen-*.tar.bz2

notifications:
  email: false
  irc:
    channels:
      - chat.freenode.net#m-labs
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
