name: litex
channels:
 - timvideos
dependencies:
 - python=3.6
 - pip
 - binutils-lm32-elf
 - gcc-lm32-elf-nostdc
 - pip:
   - git+https://github.com/m-labs/migen.git#egg=migen
   - -e .
   - git+https://github.com/enjoy-digital/liteeth.git#egg=liteeth
   - git+https://github.com/enjoy-digital/litedram.git#egg=litedram
